export { FAQSection } from "./FAQSection";
export { FeaturesSection } from "./FeaturesSection";
export { GameSection } from "./GameSection";
export type { GameSectionProps } from "./GameSection";
export { HowToPlaySection } from "./HowToPlaySection";
export { LeaderboardSection } from "./LeaderboardSection";
export type { LeaderboardSectionProps } from "./LeaderboardSection";
export { StorySection } from "./StorySection";
export { WalletSection } from "./WalletSection";
export type { WalletSectionProps } from "./WalletSection";
